[WIP] Add PHPStan
api-platform/demo pull request #166
Opened 2020-11-06 09:45 UTC by COil

| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tickets       | fixes #163 
| License       | MIT
| Doc PR        | NA. Doc in composer.json + phpstan.neon

This adds the PHPStan static analysis at the maximum level.

2020-11-09 09:10 UTC, vincentchalamon requested changes

2020-11-09 09:10 UTC, vincentchalamon commented on api/src/Entity/Parchment.php
> +    private UuidInterface $id;
```suggestion
    private ?UuidInterface $id = null;
```

2020-11-09 09:10 UTC, vincentchalamon commented on api/src/Entity/Parchment.php
> +    public string $title;
```suggestion
    public string $title = '';
```
or
```suggestion
    public ?string $title = null;
```

2020-11-09 09:10 UTC, vincentchalamon commented on api/src/Entity/Parchment.php
> +    public string $description;
```suggestion
    public string $description = '';
```
or
```suggestion
    public ?string $description = null;
```

2020-11-09 09:10 UTC, vincentchalamon commented on api/src/Entity/Review.php
> +    private UuidInterface $id;
```suggestion
    private ?UuidInterface $id = null;
```

2020-11-09 09:10 UTC, vincentchalamon commented on api/src/Entity/User.php
> +    private ?UuidInterface $id;
```suggestion
    private ?UuidInterface $id = null;
```

2020-11-09 09:10 UTC, vincentchalamon commented on api/src/Handler/BookHandler.php
> +        $imageUrl = $contents['data']['memes'][\random_int(0, 99)]['url'];
`random_int` renders a cryptographically secure value, but is slower than `mt_rand`. In this case, we don't need a secured value, so I guess it's fine to use `mt_rand` here

2020-11-09 14:03 UTC, COil commented on api/phpstan.neon
> +    - vendor/phpstan/phpstan-symfony/extension.neon
No new alert with these two plugins added.

2020-11-10 08:27 UTC, vincentchalamon approved these changes

2020-11-10 08:27 UTC, merged

2020-11-10 08:28 UTC, vincentchalamon commented
Well done @COil Thank you !